Repository kubevirt/hostpath-provisioner, pull requests merged in 2019-10, with the labels that each got.

#16 Add travis deploy infrastructure
  .gitignore
  .travis.yml
  Makefile
  deploy/kubevirt-hostpath-provisioner.yaml
  deploy/kubevirt-hostpath-security-constraints.yaml
Labels: dco-signoff: yes, size/M

#17 Set repo on deploy to quay instead of docker.
  .travis.yml
Labels: dco-signoff: yes

#18 Forgot to login before deploy
  .travis.yml
Labels: dco-signoff: yes

#15 Support Binding Mode WaitForFirstConsumer
  README.md
  cmd/provisioner/hostpath-provisioner.go
  cmd/provisioner/hostpath-provisioner_test.go
  controller/controller.go
  controller/volume.go
  deploy/kubevirt-hostpath-provisioner.yaml
Labels: dco-signoff: yes, size/L

#19 Fix deployment yamls to work.
  deploy/kubevirt-hostpath-provisioner.yaml
  deploy/kubevirt-hostpath-security-constraints.yaml
Labels: dco-signoff: yes, size/XS
