Repository kubevirt/hostpath-provisioner, pull requests merged in 2019-08, with the labels that each got.

#4 Have PV report total space as the size.
  Gopkg.lock
  hostpath-provisioner.go
Labels: size/M

#6 Add hostpath-provisioner to
  .gitignore
Labels: size/XS

#7 Add a unit test file for provisioner
  hostpath-provisioner.go
  hostpath-provisioner_test.go
Labels: size/L

#5 Verify request is not > possible PV size.
  Gopkg.lock
  hostpath-provisioner.go
  hostpath-provisioner_test.go
Labels: size/L

#8 Add test directive to Makefile
  Makefile
Labels: size/XS

#9 Add travis job to run unit tests
  .travis.yml
  Makefile
Labels: size/S

#10 Add basic linting checks
  .gitignore
  Makefile
  cmd/provisioner/hostpath-provisioner.go
  cmd/provisioner/hostpath-provisioner_test.go
  hack/.coverprofile
  hack/run-lint-checks.sh
Labels: size/L

#11 Update documentation to include how to install on Open Shift.
  README.md
  deploy/kubevirt-hostpath-provisioner.yaml
  deploy/kubevirt-hostpath-security-constraints.yaml
Labels: size/S

#13 Fix delete checking which node the PV was created on.
  cmd/provisioner/hostpath-provisioner.go
  cmd/provisioner/hostpath-provisioner_test.go
Labels: size/L

#14 Added usage.sh to show estimated usage on a particular node.
  hack/usage.sh
Labels: size/M
