Repository kubevirt/hostpath-provisioner, pull requests merged in 2023-11, with the labels that each got.

#289 [release-v0.15] Recreate go.sum to fix mismatch
  go.sum
Labels: size/XS, release-note, dco-signoff: yes, lgtm, approved

#284 [release-v0.16] Update google.golang.org/grpc to 1.56.3
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/idle.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/buffer/unbounded.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/observability.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/serviceconfig/duration.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#283 [release-v0.17] Update google.golang.org/grpc to 1.56.3
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#292 Update csi interface spec to 1.9.0
  go.mod
  go.sum
  pkg/hostpath/controllerserver.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#296 [main]feat: add .snyk file
  .snyk
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#297 [release-v0.17]feat: add .snyk file
  .snyk
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#299 [release-v0.15]feat: add .snyk file
  .snyk
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved

#298 [release-v0.16]feat: add .snyk file
  .snyk
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm, approved
