Repository kubevirt/hostpath-provisioner, pull requests merged in 2023-02, with the labels that each got.

#167 Ensure correct go with functional tests
  Makefile
  hack/run-functional-test.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#169 Single point for k8s version in makefile
  cluster-sync/clean.sh
  cluster-sync/sync.sh
  hack/k8s-e2e.sh
  hack/run-functional-test.sh
  hack/test.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#147 Specify GOARCH even when our Go is from gimme
  hack/common.sh
Labels: size/XS, release-note, dco-signoff: yes, lgtm, approved

#175 Replace deprecated k8s registry references
  deploy/csi/csi-kubevirt-hostpath-provisioner.yaml
  deploy/tests/operator.yaml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved, ok-to-test
